[package]
name = "whisper-rs-sys"
version = "0.10.0"
edition = "2021"
description = "Rust bindings for whisper.cpp (FFI bindings)"
license = "Unlicense"
documentation = "https://docs.rs/whisper-rs-sys"
repository = "https://github.com/tazz4843/whisper-rs"
links = "whisper"
include = [
    "whisper.cpp/bindings/javascript/package-tmpl.json",
    "whisper.cpp/bindings/CMakeLists.txt",
    "whisper.cpp/cmake",
    "whisper.cpp/coreml",
    "whisper.cpp/CMakeLists.txt",
    "whisper.cpp/ggml.c",
    "whisper.cpp/ggml.h",
    "whisper.cpp/ggml-alloc.c",
    "whisper.cpp/ggml-alloc.h",
    "whisper.cpp/ggml-backend.c",
    "whisper.cpp/ggml-backend.h",
    "whisper.cpp/ggml-backend-impl.h",
    "whisper.cpp/ggml-cuda.cu",
    "whisper.cpp/ggml-cuda.h",
    "whisper.cpp/ggml-impl.h",
    "whisper.cpp/ggml-metal.h",
    "whisper.cpp/ggml-metal.m",
    "whisper.cpp/ggml-metal.metal",
    "whisper.cpp/ggml-opencl.cpp",
    "whisper.cpp/ggml-opencl.h",
    "whisper.cpp/ggml-quants.h",
    "whisper.cpp/ggml-quants.c",
    "whisper.cpp/LICENSE",
    "whisper.cpp/whisper.cpp",
    "whisper.cpp/whisper.h",
    "src/*.rs",
    "build.rs",
    "wrapper.h",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
coreml = []
cuda = []
hipblas = []
opencl = []
openblas = []
metal = []
force-debug = []

[build-dependencies]
cmake = "0.1"
bindgen = "0.69"
cfg-if = "1"
fs_extra = "1.3"
